name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Print working directory
      run: pwd

    - name: List Python Files
      run: find . -name "*.py" -print

    - name: Run Python Linter
      run: |
        files=$(find . -name "*.py")
        if [ -n "$files" ]; then
          flake8 $files
        else
          echo "No Python files found to lint."
        fi

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install -g jshint

    - name: List JavaScript Files
      run: find ./server/database -name "*.js" -print

    - name: Run JavaScript Linter
      run: |
        files=$(find ./server/database -name "*.js")
        if [ -n "$files" ]; then
          jshint $files
        else
          echo "No JavaScript files found to lint."
        fi
